# Archivo: .github/workflows/python-app.yml

name: Prueba de Integración Continua

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Utiliza una acción dedicada para instalar el navegador Chrome y su driver.
    # Esta acción se encarga de la compatibilidad y la ruta automáticamente.
    - name: Instalar Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'
    
    - name: Ejecutar pruebas con Pytest y generar reporte HTML
      run: |
        pytest --html=report.html --self-contained-html

    - name: Subir reporte de prueba
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-reporte-de-prueba
        path: report.html
        
  run-tests-firefox:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Instalar Firefox
      uses: browser-actions/setup-firefox@latest
    
    - name: Ejecutar pruebas con Pytest en Firefox
      run: |
        # Añade la variable de entorno para que el driver sepa qué navegador usar.
        pytest --html=report-firefox.html --self-contained-html
      env:
        MOZ_HEADLESS: 1

    - name: Subir reporte de prueba (Firefox)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-reporte-firefox
        path: report-firefox.html

